# Generated by Django 5.1.6 on 2025-02-21 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bksbkbookshelves',
            name='bookshelf_id',
        ),
        migrations.RemoveField(
            model_name='bksbklanguages',
            name='language_id',
        ),
        migrations.RemoveField(
            model_name='bksbksubjects',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='bksbkbookshelves',
            name='bookshelf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.bksbookshelf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bksbklanguages',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.bkslanguage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bksbksubjects',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.bkssubject'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='bksbkauthors',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bksbkbookshelves',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bksbklanguages',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bksbksubjects',
            name='book',
        ),
        migrations.AddField(
            model_name='bksbkauthors',
            name='book',
            field=models.ManyToManyField(related_name='authors', to='books.bksbook'),
        ),
        migrations.AddField(
            model_name='bksbkbookshelves',
            name='book',
            field=models.ManyToManyField(related_name='shelves', to='books.bksbook'),
        ),
        migrations.AddField(
            model_name='bksbklanguages',
            name='book',
            field=models.ManyToManyField(related_name='languages', to='books.bksbook'),
        ),
        migrations.AddField(
            model_name='bksbksubjects',
            name='book',
            field=models.ManyToManyField(related_name='subjects', to='books.bksbook'),
        ),
    ]
