# Generated by Django 5.1.6 on 2025-02-21 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bksbook_author_bksbook_language_bksbook_shelves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bksbook',
            name='author',
            field=models.ManyToManyField(related_name='books', to='books.bksbkauthors'),
        ),
        migrations.AlterField(
            model_name='bksbook',
            name='language',
            field=models.ManyToManyField(related_name='books', to='books.bksbklanguages'),
        ),
        migrations.AlterField(
            model_name='bksbook',
            name='shelves',
            field=models.ManyToManyField(related_name='books', to='books.bksbkbookshelves'),
        ),
        migrations.AlterField(
            model_name='bksbook',
            name='subject',
            field=models.ManyToManyField(related_name='books', to='books.bksbksubjects'),
        ),
        migrations.AlterField(
            model_name='bksformat',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bksbook'),
        ),
    ]
